title: David Andrews
author: David Andrews
email: dha@xoba.com

description: >-
  David Andrews' personal website, featuring thoughts on technology, AI, and more.

twitter_username: broyojo42
github_username: Broyojo
linkedin_username: broyojo
youtube_username: broyojo

theme: minima
minima:
  skin: classic
